# Generated by Django 4.0.4 on 2022-05-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='Manga',
        ),
    ]
