# Generated by Django 4.0.4 on 2022-05-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.genre'),
        ),
    ]
