# Generated by Django 4.0.4 on 2022-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_manga_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='genre',
        ),
    ]
